### PR TITLE
Update for deno 1.2.0 - std: 0.61

### PR DESCRIPTION
**Pull request by avalero**
In this PR oak server import goes to 6.0.1, which uses deno std 0.61, which is used by deno 1.2.x

### CODE REVIEW

**Comment by aaronwlee** [comment]
Hi, @avalero thanks for updating it. 
I just wonder this update is really necessary due to currently oak-graphql shares a master version of the Oak.

**Comment by avalero** [comment]
Hi @aaronwlee , the problem is that oak master branch is not up to date with the last oak tag/version.
I would suggest, if that's ok with you that you tag/version oak-graphql, so that oak-graphql version can be mapped to a precise oak tag/version, and consequently, mapped to a deno version.

By the way, great job!!

**Comment by aaronwlee** [comment]
then how about this solution,
we're currently importing the mod.ts file, instead of this receive the Router class as a value

current
```ts
const GraphQLService = await applyGraphQL({
  typeDefs: types,
  resolvers: resolvers,
  context: (ctx) => {
    return { user: "Aaron" };
  }
})
```

suggestion
```ts
const GraphQLService = await applyGraphQL({
  version: Router,
  typeDefs: types,
  resolvers: resolvers,
  context: (ctx) => {
    return { user: "Aaron" };
  }
})
```

What do you think about it? I'd like to get your opinions.

**Comment by avalero** [comment]
That's certainly a good one!! It's a great way to "uncouple" from the Router!!

**Comment by aaronwlee** [comment]
@avalero I've updated it :) Thanks for your help 👍

**Pull request closed without merging**
